# Generated by Django 3.2.6 on 2021-08-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sideLeft', models.PositiveIntegerField()),
                ('sideRight', models.PositiveIntegerField()),
                ('sideTop', models.PositiveIntegerField()),
                ('sideBottom', models.PositiveIntegerField()),
                ('diagonalLength_1', models.PositiveIntegerField()),
                ('diagonalLength_2', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sideLeft', models.PositiveIntegerField()),
                ('sideRight', models.PositiveIntegerField()),
                ('sideTop', models.PositiveIntegerField()),
                ('sideBottom', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sideLeft', models.PositiveIntegerField()),
                ('sideRight', models.PositiveIntegerField()),
                ('sideTop', models.PositiveIntegerField()),
                ('sideBottom', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseLength', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('side1', models.PositiveIntegerField()),
                ('side2', models.PositiveIntegerField()),
                ('side3', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
